/*
 * This file is generated by jOOQ.
 */
package org.nitesh.jOOQ.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long authorId;
    private Long bookId;

    public AuthorBook() {}

    public AuthorBook(AuthorBook value) {
        this.authorId = value.authorId;
        this.bookId = value.bookId;
    }

    public AuthorBook(
        Long authorId,
        Long bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    /**
     * Getter for <code>AUTHOR_BOOK.AUTHOR_ID</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>AUTHOR_BOOK.AUTHOR_ID</code>.
     */
    public AuthorBook setAuthorId(Long authorId) {
        this.authorId = authorId;
        return this;
    }

    /**
     * Getter for <code>AUTHOR_BOOK.BOOK_ID</code>.
     */
    public Long getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>AUTHOR_BOOK.BOOK_ID</code>.
     */
    public AuthorBook setBookId(Long bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuthorBook other = (AuthorBook) obj;
        if (authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!authorId.equals(other.authorId))
            return false;
        if (bookId == null) {
            if (other.bookId != null)
                return false;
        }
        else if (!bookId.equals(other.bookId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.bookId == null) ? 0 : this.bookId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
