/*
 * This file is generated by jOOQ.
 */
package org.nitesh.jOOQ.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private String  firstName;
    private String  lastName;
    private Integer version;

    public Author() {}

    public Author(Author value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.version = value.version;
    }

    public Author(
        Long    id,
        String  firstName,
        String  lastName,
        Integer version
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.version = version;
    }

    /**
     * Getter for <code>AUTHOR.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>AUTHOR.ID</code>.
     */
    public Author setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>AUTHOR.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>AUTHOR.FIRST_NAME</code>.
     */
    public Author setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>AUTHOR.LAST_NAME</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>AUTHOR.LAST_NAME</code>.
     */
    public Author setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>AUTHOR.VERSION</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>AUTHOR.VERSION</code>.
     */
    public Author setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Author other = (Author) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!firstName.equals(other.firstName))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!lastName.equals(other.lastName))
            return false;
        if (version == null) {
            if (other.version != null)
                return false;
        }
        else if (!version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
