/*
 * This file is generated by jOOQ.
 */
package org.nitesh.jOOQ.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long      id;
    private LocalDate publishingdate;
    private String    title;
    private Integer   version;

    public Book() {}

    public Book(Book value) {
        this.id = value.id;
        this.publishingdate = value.publishingdate;
        this.title = value.title;
        this.version = value.version;
    }

    public Book(
        Long      id,
        LocalDate publishingdate,
        String    title,
        Integer   version
    ) {
        this.id = id;
        this.publishingdate = publishingdate;
        this.title = title;
        this.version = version;
    }

    /**
     * Getter for <code>BOOK.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>BOOK.ID</code>.
     */
    public Book setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>BOOK.PUBLISHINGDATE</code>.
     */
    public LocalDate getPublishingdate() {
        return this.publishingdate;
    }

    /**
     * Setter for <code>BOOK.PUBLISHINGDATE</code>.
     */
    public Book setPublishingdate(LocalDate publishingdate) {
        this.publishingdate = publishingdate;
        return this;
    }

    /**
     * Getter for <code>BOOK.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>BOOK.TITLE</code>.
     */
    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>BOOK.VERSION</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>BOOK.VERSION</code>.
     */
    public Book setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Book other = (Book) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (publishingdate == null) {
            if (other.publishingdate != null)
                return false;
        }
        else if (!publishingdate.equals(other.publishingdate))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (version == null) {
            if (other.version != null)
                return false;
        }
        else if (!version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.publishingdate == null) ? 0 : this.publishingdate.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(publishingdate);
        sb.append(", ").append(title);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
