/*
 * This file is generated by jOOQ.
 */
package org.nitesh.jOOQ;


import org.nitesh.jOOQ.tables.Author;
import org.nitesh.jOOQ.tables.AuthorBook;
import org.nitesh.jOOQ.tables.Book;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>AUTHOR_BOOK</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
